### PR TITLE
Add GPL3 licensing to source files

### PR DESCRIPTION
**Pull request by karfai**
Connects to #1

Change-Id: I21733d3cf68fac3ca0dad5091e16f236bd91713b

### CODE REVIEW

**Comment by jpotvin** [comment]
Acknowledgements: Work on this files has been carried out in collaboration with PersonA and PersonB.

Copyright (C) year1, year2, year3 copyright-holder

This file is part of Lichen.

Lichen is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Lichen is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Lichen.  If not, see <http://www.gnu.org/licenses/>.

**Comment by karfai** [comment]
I think the Acknowledgements is suitable for the README, not the code itself.

**Comment by jpotvin** [comment]
The thing is, copyright covers the legal aspects of expression, and acknowledgements is relevant to the legal aspects of "prior art".  For that 2nd reason too, I suggest both. But here's a shortened way:

// Acknowledgements: Funds: Xalgorithms Foundation. Collaborators: Don Kelly, Joseph Potvin and Bill Olders. Context: This file is part of Lichen, a functional component of an Internet of Rules (IoR).

**Comment by karfai** [comment]
But, still, it's part of Interlibr. Not Lichen. This is platform library.

**Comment by jpotvin** [comment]
Oh, I was just putting "Lichen" there as an example within the text -- sure, change that.

**Comment by karfai** [comment]
```// Copyright (C) 2018 Don Kelly <karfai@gmail.com>
// Copyright (C) 2018 Hayk Pilosyan <hayk.pilos@gmail.com>

// This file is part of Interlibr, a functional component of an
// Internet of Rules (IoR).

// ACKNOWLEDGEMENTS
// Funds: Xalgorithms Foundation
// Collaborators: Don Kelly, Joseph Potvin and Bill Olders.

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.

// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
```

How's this?

**Comment by jpotvin** [comment]
Good -- let's add the URL to Xalgorithms Foundation https://xalgorithms.org

**Pull request merged**
